export default function Privacy() {
  return (
    <main style={{ maxWidth: 640, margin: "0 auto", padding: "48px 20px", lineHeight: 1.7 }}>
      <h1 style={{ fontSize: 28, fontWeight: 800 }}>Privacy Policy — Explicare</h1>
      <p style={{ opacity: 0.6, fontSize: 14 }}>Last updated: September 2026</p>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>What we do with your photo</h2>
      <p>
        When you photograph a medicine label, package insert, prescription, or lab result, the
        image is sent, encrypted in transit, to generate the plain-language explanation using a
        third-party artificial intelligence service (Groq). The image is processed in memory to
        generate that response and is not stored on Explicare's servers afterward. We do not use
        your photos to train any AI models.
      </p>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>What stays on your device</h2>
      <p>
        Your history of explained items (medication or lab result name, the explanation, and,
        if you choose, the photo) is saved only locally on your phone, in a local database
        (SQLite). We have no access to this history and it is never sent to any server of ours.
        If you uninstall the app or clear its data, this history is deleted as well.
      </p>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>Subscriptions and purchases</h2>
      <p>
        Premium subscriptions are processed by Apple, Google, or Samsung (depending on which
        store you downloaded the app from) and technically managed by RevenueCat, which receives
        only the data necessary to validate your purchase (an anonymous user identifier and
        subscription status) — never credit card data, which stays with the app store itself.
      </p>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>What we do NOT do</h2>
      <ul style={{ paddingLeft: 20 }}>
        <li>We do not show third-party ads.</li>
        <li>We do not sell or share your data with advertisers.</li>
        <li>We do not require sign-up, login, or an email address to use the app's core features.</li>
        <li>We do not track your location.</li>
      </ul>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>Children</h2>
      <p>
        Explicare is not directed at children and does not knowingly collect data from anyone
        under 13.
      </p>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>Medical disclaimer</h2>
      <p>
        Explicare is not a medical device and does not diagnose, treat, cure, or prevent any
        medical condition. Explanations are generated by artificial intelligence and are an
        educational, plain-language summary — always confirm any decision about medication or
        lab results with a licensed doctor or pharmacist.
      </p>

      <h2 style={{ fontSize: 19, fontWeight: 700, marginTop: 28 }}>Contact</h2>
      <p>
        Privacy questions: <a href="mailto:cortextechbr@gmail.com">cortextechbr@gmail.com</a>
      </p>
    </main>
  );
}
